#database connection settings
spring.application.name=wia1002_bus_route_tracking
spring.datasource.url=jdbc:postgresql://localhost:5432/bus_tracker_db
spring.datasource.username=postgres
spring.datasource.password=admin123

# This dialect tells Hibernate to use PostGIS functions
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true




